1. Pré-processamento dos dados e preparação do dataset.

In [100]:
import pandas as pd

# Para acessar o arquivo, basta fazer o download dos microdados no seguinte endereço: https://download.inep.gov.br/microdados/microdados_enem_2024.zip
# O arquivo "RESULTADOS_2024.csv" encontra-se na pasta DADOS.

# Devido ao seu tamanho excessivamente grande, o GitHub não permite o armzenamento do arquivo no repositório;
# logo, deve-se fazer o download dos microdados e rodar localmente.

PATH_ENEM = "data/RESULTADOS_2024.csv"

# Carregar os dados
df_enem = pd.read_csv(
    PATH_ENEM,
    sep=";",
    encoding="latin1",
    low_memory=False
)

display(df_enem.head())
display(df_enem.info())
print("Dados carregados com sucesso!")

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,3604651,2024,42103770.0,4218004.0,Tijucas,42.0,SC,4.0,1.0,1.0,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,200.0,180.0,180.0,920.0
2,1461268,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,120.0,120.0,40.0,120.0,80.0,480.0
3,4301058,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,140.0,200.0,160.0,160.0,80.0,740.0
4,3148322,2024,21150354.0,2100436.0,Alto Alegre do Maranhão,21.0,MA,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4332944 entries, 0 to 4332943
Data columns (total 42 columns):
 #   Column                  Dtype
---  ------                  -----
 0   NU_SEQUENCIAL           int64
 1   NU_ANO                  int64
 2   CO_ESCOLA               float64
 3   CO_MUNICIPIO_ESC        float64
 4   NO_MUNICIPIO_ESC        object
 5   CO_UF_ESC               float64
 6   SG_UF_ESC               object
 7   TP_DEPENDENCIA_ADM_ESC  float64
 8   TP_LOCALIZACAO_ESC      float64
 9   TP_SIT_FUNC_ESC         float64
 10  CO_MUNICIPIO_PROVA      int64
 11  NO_MUNICIPIO_PROVA      object
 12  CO_UF_PROVA             int64
 13  SG_UF_PROVA             object
 14  TP_PRESENCA_CN          int64
 15  TP_PRESENCA_CH          int64
 16  TP_PRESENCA_LC          int64
 17  TP_PRESENCA_MT          int64
 18  CO_PROVA_CN             float64
 19  CO_PROVA_CH             float64
 20  CO_PROVA_LC             float64
 21  CO_PROVA_MT             float64
 22  NU_NOTA_CN              float64
 23  NU_NOTA_CH              float64
 24  NU_NOTA_LC              float64
 25  NU_NOTA_MT              float64
 26  TX_RESPOSTAS_CN         object
 27  TX_RESPOSTAS_CH         object
 28  TX_RESPOSTAS_LC         object
 29  TX_RESPOSTAS_MT         object
 30  TP_LINGUA               int64
 31  TX_GABARITO_CN          object
 32  TX_GABARITO_CH          object
 33  TX_GABARITO_LC          object
 34  TX_GABARITO_MT          object
 35  TP_STATUS_REDACAO       float64
 36  NU_NOTA_COMP1           float64
 37  NU_NOTA_COMP2           float64
 38  NU_NOTA_COMP3           float64
 39  NU_NOTA_COMP4           float64
 40  NU_NOTA_COMP5           float64
 41  NU_NOTA_REDACAO         float64
dtypes: float64(21), int64(9), object(12)
memory usage: 1.4+ GB

None

Dados carregados com sucesso!

In [101]:
# Excluir colunas irrelevantes.
df_enem = df_enem.drop(columns=[
                                'NU_SEQUENCIAL', 'NU_ANO', 'CO_MUNICIPIO_ESC', 'CO_UF_ESC', 'CO_MUNICIPIO_PROVA', 'CO_UF_PROVA',
                                'TP_DEPENDENCIA_ADM_ESC',	'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'TP_PRESENCA_CN',
                                'TP_PRESENCA_CH',	'TP_PRESENCA_LC','TP_PRESENCA_MT',	'CO_PROVA_CN',	'CO_PROVA_CH',	'CO_PROVA_LC',
                                'CO_PROVA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT',
                                'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT',
                                'TP_STATUS_REDACAO',	'NU_NOTA_COMP1',	'NU_NOTA_COMP2',	'NU_NOTA_COMP3',	'NU_NOTA_COMP4',	'NU_NOTA_COMP5'
                                ]
                       )
display(df_enem.head())
print("Colunas excluídas com sucesso!")

,CO_ESCOLA,NO_MUNICIPIO_ESC,SG_UF_ESC,NO_MUNICIPIO_PROVA,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,23052929.0,Aratuba,CE,Aratuba,CE,436.8,377.8,423.4,427.1,300.0
1,42103770.0,Tijucas,SC,Tijucas,SC,521.9,601.9,605.5,689.2,920.0
2,NaN,NaN,NaN,Rolândia,PR,363.0,548.4,557.2,456.4,480.0
3,NaN,NaN,NaN,Osasco,SP,550.7,553.8,605.9,629.1,740.0
4,21150354.0,Alto Alegre do Maranhão,MA,São Mateus do Maranhão,MA,NaN,NaN,NaN,NaN,NaN

Colunas excluídas com sucesso!

In [102]:
# Renomear as colunas, para tornar a análise mais intuitiva.
df_enem = df_enem.rename(columns=
    {
    "CO_ESCOLA": "codigo_escola",
    "NO_MUNICIPIO_ESC": "municipio_escola",
    "SG_UF_ESC": "uf_escola",
    "NO_MUNICIPIO_PROVA": "municipio_prova",
    "SG_UF_PROVA": "uf_prova",
    "NU_NOTA_CN": "nota_ciencias_natureza",
    "NU_NOTA_CH": "nota_ciencias_humanas",
    "NU_NOTA_LC": "nota_linguagens_codigos",
    "NU_NOTA_MT": "nota_matematica",
    "NU_NOTA_REDACAO": "nota_redacao"
    }
                         )

display(df_enem.head())
print("Colunas renomeadas com sucesso!")

,codigo_escola,municipio_escola,uf_escola,municipio_prova,uf_prova,nota_ciencias_natureza,nota_ciencias_humanas,nota_linguagens_codigos,nota_matematica,nota_redacao
0,23052929.0,Aratuba,CE,Aratuba,CE,436.8,377.8,423.4,427.1,300.0
1,42103770.0,Tijucas,SC,Tijucas,SC,521.9,601.9,605.5,689.2,920.0
2,NaN,NaN,NaN,Rolândia,PR,363.0,548.4,557.2,456.4,480.0
3,NaN,NaN,NaN,Osasco,SP,550.7,553.8,605.9,629.1,740.0
4,21150354.0,Alto Alegre do Maranhão,MA,São Mateus do Maranhão,MA,NaN,NaN,NaN,NaN,NaN

Colunas renomeadas com sucesso!

In [103]:
# Converter o tipo da coluna 'codigo_escola' para 'Int64'.
df_enem["codigo_escola"] = df_enem["codigo_escola"].astype('Int64')

display(df_enem.info())
print("Tipo da coluna 'codigo_escola' convertido com sucesso!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4332944 entries, 0 to 4332943
Data columns (total 10 columns):
 #   Column                   Dtype
---  ------                   -----
 0   codigo_escola            Int64
 1   municipio_escola         object
 2   uf_escola                object
 3   municipio_prova          object
 4   uf_prova                 object
 5   nota_ciencias_natureza   float64
 6   nota_ciencias_humanas    float64
 7   nota_linguagens_codigos  float64
 8   nota_matematica          float64
 9   nota_redacao             float64
dtypes: Int64(1), float64(5), object(4)
memory usage: 334.7+ MB

None

Tipo da coluna 'codigo_escola' convertido com sucesso!

In [104]:
# Filtrar SP nas colunas 'uf_escola' e 'uf_prova'
df_enem_sp_escola = df_enem[df_enem["uf_escola"] == "SP"].copy()
df_enem_sp_prova = df_enem[df_enem["uf_prova"] == "SP"].copy()

In [105]:
display(df_enem_sp_escola.info())

print("""Com o filtro pela coluna da escola, são retornadas 285199 linhas,
correspondentes aos candidatos concluintes do Ensino Médio em escolas paulistas.""")

<class 'pandas.core.frame.DataFrame'>
Index: 285199 entries, 36 to 4332941
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   codigo_escola            285199 non-null  Int64
 1   municipio_escola         285199 non-null  object
 2   uf_escola                285199 non-null  object
 3   municipio_prova          285199 non-null  object
 4   uf_prova                 285199 non-null  object
 5   nota_ciencias_natureza   217717 non-null  float64
 6   nota_ciencias_humanas    225991 non-null  float64
 7   nota_linguagens_codigos  225991 non-null  float64
 8   nota_matematica          217717 non-null  float64
 9   nota_redacao             225991 non-null  float64
dtypes: Int64(1), float64(5), object(4)
memory usage: 24.2+ MB

None

Com o filtro pela coluna da escola, são retornadas 285199 linhas,
correspondentes aos candidatos concluintes do Ensino Médio em escolas paulistas.

In [106]:
display(df_enem_sp_prova.info())

print("""Com o filtro pela coluna da prova, são retornadas 647215 linhas, correspondentes a todos os candidatos - não considerando faixa etária
ou vinculação formal com escola, por exemplo - que realizaram as provas em cidades do estado de São Paulo.""")

print("""Uma vez que a amplitude de faixas etárias pode representar diferentes realidades sociais - de tentativas de ingresso tardio, devido à
diferentes razões, à postulantes à segunda graduação - e como o intuito último da presente pesquisa é a construção de um modelo inicial
que possa embasar políticas públicas a partir das análises, optou-se por delimitá-la apenas aos concluintes do Ensino Médio, por entender
que a faixa etária fornece um solo comum mais homogêneo. Nada impede, contudo, que retomemos esse modelo inicial posteriormente, alterando
o foco da abordagem. Assim, nas próximas células, será utilizado apenas o DataFrame 'df_enem_sp_escola'.""")

<class 'pandas.core.frame.DataFrame'>
Index: 647215 entries, 3 to 4332943
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   codigo_escola            285599 non-null  Int64
 1   municipio_escola         285599 non-null  object
 2   uf_escola                285599 non-null  object
 3   municipio_prova          647215 non-null  object
 4   uf_prova                 647215 non-null  object
 5   nota_ciencias_natureza   466821 non-null  float64
 6   nota_ciencias_humanas    488738 non-null  float64
 7   nota_linguagens_codigos  488738 non-null  float64
 8   nota_matematica          466821 non-null  float64
 9   nota_redacao             488738 non-null  float64
dtypes: Int64(1), float64(5), object(4)
memory usage: 54.9+ MB

None

Com o filtro pela coluna da prova, são retornadas 647215 linhas, correspondentes a todos os candidatos - não considerando faixa etária
ou vinculação formal com escola, por exemplo - que realizaram as provas em cidades do estado de São Paulo.
Uma vez que a amplitude de faixas etárias pode representar diferentes realidades sociais - de tentativas de ingresso tardio, devido à
diferentes razões, à postulantes à segunda graduação - e como o intuito último da presente pesquisa é a construção de um modelo inicial
que possa embasar políticas públicas a partir das análises, optou-se por delimitá-la apenas aos concluintes do Ensino Médio, por entender
que a faixa etária fornece um solo comum mais homogêneo. Nada impede, contudo, que retomemos esse modelo inicial posteriormente, alterando
o foco da abordagem. Assim, nas próximas células, será utilizado apenas o DataFrame 'df_enem_sp_escola'.

In [107]:
# Reorganizar as colunas.
# Excluir colunas obsoletas: 'uf_escola', 'municipio_prova' e 'uf_prova'.
df_enem_sp_escola = df_enem_sp_escola.drop(columns=['uf_escola', 'municipio_prova', 'uf_prova'])

# Renomear a coluna 'municipio_escola' para 'municipio', simplificando a compreensão.
df_enem_sp_escola = df_enem_sp_escola.rename(columns={'municipio_escola': 'municipio'})

display(df_enem_sp_escola.head())
print("Colunas reorganizadas com sucesso!")

,codigo_escola,municipio,nota_ciencias_natureza,nota_ciencias_humanas,nota_linguagens_codigos,nota_matematica,nota_redacao
36,35150344,Itapecerica da Serra,447.4,591.2,586.9,538.3,480.0
39,35109411,Osasco,408.1,547.7,518.9,591.4,840.0
40,35569409,Sorocaba,592.3,663.2,617.8,786.1,820.0
53,35925500,São Paulo,NaN,NaN,NaN,NaN,NaN
63,35033522,Fernão,545.5,542.0,544.7,451.4,560.0

Colunas reorganizadas com sucesso!

In [108]:
# Criar média das notas das provas objetivas - já que a nota da prova de redação, dada a sua natureza particular, deveria ser analisada de maneira isolada.
df_enem_sp_escola["media_notas_objetivas"] = df_enem_sp_escola[
    ["nota_ciencias_natureza", "nota_ciencias_humanas", "nota_linguagens_codigos", "nota_matematica"]
].mean(axis=1)

display(df_enem_sp_escola.head())
print("Coluna 'media_notas_objetivas' criada com sucesso!")

,codigo_escola,municipio,nota_ciencias_natureza,nota_ciencias_humanas,nota_linguagens_codigos,nota_matematica,nota_redacao,media_notas_objetivas
36,35150344,Itapecerica da Serra,447.4,591.2,586.9,538.3,480.0,540.950
39,35109411,Osasco,408.1,547.7,518.9,591.4,840.0,516.525
40,35569409,Sorocaba,592.3,663.2,617.8,786.1,820.0,664.850
53,35925500,São Paulo,NaN,NaN,NaN,NaN,NaN,NaN
63,35033522,Fernão,545.5,542.0,544.7,451.4,560.0,520.900

Coluna 'media_notas_objetivas' criada com sucesso!

In [109]:
# Arredondar a coluna 'media_notas_objetivas' para uma casa decimal.
df_enem_sp_escola['media_notas_objetivas'] = df_enem_sp_escola['media_notas_objetivas'].round(1)

display(df_enem_sp_escola.head())
print("Coluna 'media_notas_objetivas' arredondada para uma casa decimal com sucesso!")

,codigo_escola,municipio,nota_ciencias_natureza,nota_ciencias_humanas,nota_linguagens_codigos,nota_matematica,nota_redacao,media_notas_objetivas
36,35150344,Itapecerica da Serra,447.4,591.2,586.9,538.3,480.0,541.0
39,35109411,Osasco,408.1,547.7,518.9,591.4,840.0,516.5
40,35569409,Sorocaba,592.3,663.2,617.8,786.1,820.0,664.8
53,35925500,São Paulo,NaN,NaN,NaN,NaN,NaN,NaN
63,35033522,Fernão,545.5,542.0,544.7,451.4,560.0,520.9

Coluna 'media_notas_objetivas' arredondada para uma casa decimal com sucesso!

In [110]:
# Remover candidatos ausentes.
# Candidatos ausentes nos 2 dias.
df_enem_sp_escola = df_enem_sp_escola[df_enem_sp_escola["media_notas_objetivas"].notna()]
# Candidatos ausentes no 1o dia (Exatas).
df_enem_sp_escola = df_enem_sp_escola[df_enem_sp_escola["nota_matematica"].notna()]
# Candidatos ausentes no 2o dia (Humanas).
df_enem_sp_escola = df_enem_sp_escola[df_enem_sp_escola["nota_ciencias_humanas"].notna()]

display(df_enem_sp_escola.info())
print("Candidatos ausentes excluídos com sucesso!")

<class 'pandas.core.frame.DataFrame'>
Index: 217057 entries, 36 to 4332941
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   codigo_escola            217057 non-null  Int64
 1   municipio                217057 non-null  object
 2   nota_ciencias_natureza   217057 non-null  float64
 3   nota_ciencias_humanas    217057 non-null  float64
 4   nota_linguagens_codigos  217057 non-null  float64
 5   nota_matematica          217057 non-null  float64
 6   nota_redacao             217057 non-null  float64
 7   media_notas_objetivas    217057 non-null  float64
dtypes: Int64(1), float64(6), object(1)
memory usage: 15.1+ MB

None

Candidatos ausentes excluídos com sucesso!

In [111]:
# Para acessar o arquivo com a lista das escolas de acordo com o 'Código INEP', basta acessar o seguinte endereço: http://anonymousdata.inep.gov.br/analytics/saw.dll?Portal.
# Uma vez nele, basta aplicar o filtro desejado - em nosso caso, UF == SP - e exportar para um arquivo .csv.

# Como o arquivo é pequeno, mantemos uma cópia no repositório do GitHub.

PATH_ESCOLAS = "data/lista_escolas.csv"

# Carregar os dados
df_escolas = pd.read_csv(
    PATH_ESCOLAS,
    sep=",",
    encoding="utf-8",
    low_memory=False
)

display(df_escolas.info())
print("Dados carregados com sucesso!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8222 entries, 0 to 8221
Data columns (total 19 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Restrição de Atendimento                  8222 non-null   object
 1   Escola                                    8222 non-null   object
 2   Código INEP                               8222 non-null   int64
 3   UF                                        8222 non-null   object
 4   Município                                 8222 non-null   object
 5   Localização                               8222 non-null   object
 6   Localidade Diferenciada                   8222 non-null   object
 7   Categoria Administrativa                  8222 non-null   object
 8   Endereço                                  8222 non-null   object
 9   Telefone                                  8039 non-null   object
 10  Dependência Administrativa                8222 non-null   object
 11  Categoria Escola Privada                  8222 non-null   object
 12  Conveniada Poder Público                  8222 non-null   object
 13  Regulamentação pelo Conselho de Educação  8222 non-null   object
 14  Porte da Escola                           8222 non-null   object
 15  Etapas e Modalidade de Ensino Oferecidas  8222 non-null   object
 16  Outras Ofertas Educacionais               3005 non-null   object
 17  Latitude                                  8222 non-null   object
 18  Longitude                                 8222 non-null   object
dtypes: int64(1), object(18)
memory usage: 1.2+ MB

None

Dados carregados com sucesso!

In [112]:
# Converter a coluna 'Código INEP' em df_escolas para o tipo Int64 para compatibilidade com 'codigo_escola'.
df_escolas['Código INEP'] = df_escolas['Código INEP'].astype('Int64')

display(df_escolas.info())
print("Tipo da coluna 'Código INEP' convertido com sucesso!")

# Realizar o merge para adicionar as colunas com os detalhes das escolas.
df_enem_sp_escola = pd.merge(
    df_enem_sp_escola,
    df_escolas[['Código INEP', 'Categoria Administrativa', 'Dependência Administrativa', 'Categoria Escola Privada']],
    left_on='codigo_escola',
    right_on='Código INEP',
    how='left'
)

# Excluir as colunas 'Código INEP', redundante do merge, e 'codigo_escola', doravante desnecessária.
df_enem_sp_escola = df_enem_sp_escola.drop(columns=['Código INEP', 'codigo_escola'])

display(df_enem_sp_escola.head())
print("Colunas sobre as escolas adicionadas com sucesso!")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8222 entries, 0 to 8221
Data columns (total 19 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Restrição de Atendimento                  8222 non-null   object
 1   Escola                                    8222 non-null   object
 2   Código INEP                               8222 non-null   Int64
 3   UF                                        8222 non-null   object
 4   Município                                 8222 non-null   object
 5   Localização                               8222 non-null   object
 6   Localidade Diferenciada                   8222 non-null   object
 7   Categoria Administrativa                  8222 non-null   object
 8   Endereço                                  8222 non-null   object
 9   Telefone                                  8039 non-null   object
 10  Dependência Administrativa                8222 non-null   object
 11  Categoria Escola Privada                  8222 non-null   object
 12  Conveniada Poder Público                  8222 non-null   object
 13  Regulamentação pelo Conselho de Educação  8222 non-null   object
 14  Porte da Escola                           8222 non-null   object
 15  Etapas e Modalidade de Ensino Oferecidas  8222 non-null   object
 16  Outras Ofertas Educacionais               3005 non-null   object
 17  Latitude                                  8222 non-null   object
 18  Longitude                                 8222 non-null   object
dtypes: Int64(1), object(18)
memory usage: 1.2+ MB

None

Tipo da coluna 'Código INEP' convertido com sucesso!

,municipio,nota_ciencias_natureza,nota_ciencias_humanas,nota_linguagens_codigos,nota_matematica,nota_redacao,media_notas_objetivas,Categoria Administrativa,Dependência Administrativa,Categoria Escola Privada
0,Itapecerica da Serra,447.4,591.2,586.9,538.3,480.0,541.0,Privada,Privada,Particular
1,Osasco,408.1,547.7,518.9,591.4,840.0,516.5,Privada,Privada,Filantrópica
2,Sorocaba,592.3,663.2,617.8,786.1,820.0,664.8,Privada,Privada,Particular
3,Fernão,545.5,542.0,544.7,451.4,560.0,520.9,Pública,Estadual,Não Informado
4,Piracicaba,624.9,547.5,599.6,699.7,780.0,617.9,Privada,Privada,Particular

Colunas sobre as escolas adicionadas com sucesso!

In [113]:
# Renomear novas colunas.
df_enem_sp_escola = df_enem_sp_escola.rename(columns=
    {
     "Categoria Administrativa": "cat_adm",
     "Dependência Administrativa": "dep_adm",
     "Categoria Escola Privada": "cat_esc_priv"
    }
                                             )

display(df_enem_sp_escola.head())
print("Colunas renomeadas com sucesso!")

,municipio,nota_ciencias_natureza,nota_ciencias_humanas,nota_linguagens_codigos,nota_matematica,nota_redacao,media_notas_objetivas,cat_adm,dep_adm,cat_esc_priv
0,Itapecerica da Serra,447.4,591.2,586.9,538.3,480.0,541.0,Privada,Privada,Particular
1,Osasco,408.1,547.7,518.9,591.4,840.0,516.5,Privada,Privada,Filantrópica
2,Sorocaba,592.3,663.2,617.8,786.1,820.0,664.8,Privada,Privada,Particular
3,Fernão,545.5,542.0,544.7,451.4,560.0,520.9,Pública,Estadual,Não Informado
4,Piracicaba,624.9,547.5,599.6,699.7,780.0,617.9,Privada,Privada,Particular

Colunas renomeadas com sucesso!

In [114]:
# Identificar linhas onde 'cat_adm' é nula.
linhas_nulas_cat_adm = df_enem_sp_escola[df_enem_sp_escola['cat_adm'].isnull()]

print("Linhas onde 'cat_adm' é nula (primeiras 5):")
display(linhas_nulas_cat_adm.head())
print(f"Total de linhas nulas na coluna 'cat_adm': {len(linhas_nulas_cat_adm)}")

Linhas onde 'cat_adm' é nula (primeiras 5):

,municipio,nota_ciencias_natureza,nota_ciencias_humanas,nota_linguagens_codigos,nota_matematica,nota_redacao,media_notas_objetivas,cat_adm,dep_adm,cat_esc_priv
153,São Paulo,538.5,491.1,588.5,527.4,700.0,536.4,NaN,NaN,NaN
433,Piracicaba,496.2,604.5,572.0,669.1,620.0,585.4,NaN,NaN,NaN
507,Araraquara,389.3,517.6,532.7,471.9,660.0,477.9,NaN,NaN,NaN
530,Itapetininga,429.7,476.4,534.8,454.6,640.0,473.9,NaN,NaN,NaN
653,São Paulo,607.4,663.9,627.0,659.0,840.0,639.3,NaN,NaN,NaN

Total de linhas nulas na coluna 'cat_adm': 2876

In [115]:
# Excluir as linhas em que o código da escola não corresponde ao código da base do INEP da escola, pois essa imprecisão pode distorcer os dados.
df_enem_sp_escola = df_enem_sp_escola.dropna(subset=['cat_adm'])

display(df_enem_sp_escola.info())
print("Linhas com 'cat_adm' nulas excluídas com sucesso!")

<class 'pandas.core.frame.DataFrame'>
Index: 214181 entries, 0 to 217056
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   municipio                214181 non-null  object
 1   nota_ciencias_natureza   214181 non-null  float64
 2   nota_ciencias_humanas    214181 non-null  float64
 3   nota_linguagens_codigos  214181 non-null  float64
 4   nota_matematica          214181 non-null  float64
 5   nota_redacao             214181 non-null  float64
 6   media_notas_objetivas    214181 non-null  float64
 7   cat_adm                  214181 non-null  object
 8   dep_adm                  214181 non-null  object
 9   cat_esc_priv             214181 non-null  object
dtypes: float64(6), object(4)
memory usage: 18.0+ MB

None

Linhas com 'cat_adm' nulas excluídas com sucesso!

In [116]:
# Exportar 'df_enem_sp_escola'
df_enem_sp_escola.to_csv('data/df_enem_sp.csv', index=False)
print("DataFrame 'df_enem_sp_escola.csv' exportado com sucesso para 'data/df_enem_sp.csv'.")

DataFrame 'df_enem_sp_escola.csv' exportado com sucesso para 'data/df_enem_sp.csv'.

In [117]:
# Agrupar os dados por município.
base_municipio = (
    df_enem_sp_escola.groupby("municipio")
    .agg(
        media_notas=("media_notas_objetivas", "mean"),
        total_participantes=("media_notas_objetivas", "size"),
        desvio_notas=("media_notas_objetivas", "std")
    )
    .reset_index()
)

# Arredondar as colunas 'media_notas' e 'desvio_notas' para uma casa decimal
base_municipio['media_notas'] = base_municipio['media_notas'].round(1)
base_municipio['desvio_notas'] = base_municipio['desvio_notas'].round(1)

display(base_municipio.head())
print("DataFrame 'base_municipio' criado com sucesso!")

    municipio  media_notas  total_participantes  desvio_notas
0  Adamantina        547.7                  142          68.8
1      Adolfo        501.0                   13          56.7
2       Aguaí        492.8                   95          55.7
3      Agudos        535.2                  136          65.4
4    Alambari        480.9                   18          42.7

DataFrame 'base_municipio' criado com sucesso!

In [118]:
# Será utilizada apenas uma amostra, com os 200 municípios com mais participantes na prova, para alimentar os algoritmos de regressão.
# Isso posto, ordena-se os municípios pela coluna 'total_participantes' de maneira decrescente.
base_municipio = base_municipio.sort_values(by='total_participantes', ascending=False).reset_index(drop=True)

# Selecionar os 200 primeiros municípios, que serão a base para a constituição do arquivo 'censo_2022.csv'.
base_municipio_top200 = base_municipio['municipio'].head(200).copy()
print("DataFrame 'base_municipio_top200' criado com sucesso!")

print("Os 200 primeiros municípios com mais participantes são:")
display(base_municipio_top200.head(200))

# Exportar a lista dos 200 primeiros municípios.
# base_municipio_top200.to_csv('data/base_municipio_top200.csv', index=False)
# print("DataFrame 'base_municipio_top200' exportado com sucesso para 'data/base_municipio_top200.csv'.")
print("A linha que exporta o DataFrame foi comentada, uma vez que o arquivo é temporário.")

DataFrame 'base_municipio_top200' criado com sucesso!
Os 200 primeiros municípios com mais participantes são:

0                     São Paulo
1                     Guarulhos
2                      Campinas
3         São Bernardo do Campo
4           São José dos Campos
                 ...
195              Rio das Pedras
196                Pilar do Sul
197          Araçoiaba da Serra
198    Santa Cruz das Palmeiras
199                     Ipaussu
Name: municipio, Length: 200, dtype: object

A linha que exporta o DataFrame foi comentada, uma vez que o arquivo é temporário.

In [119]:
print("""Em respeito à LGPD, o INEP dividiu os microdados da edição de 2024 em dois datasets: um com os dados socioeconômicos indivduais dos participantes
e um com os resultados das provas, sem chave de conexão entre eles. Isso limita bastante a pesquisa aplicada: foi preciso, por exemplo,
trabalhar apenas com variáveis a nível municipal, extraídas do Censo 2022, realizado pelo IBGE, que ainda permitem investigar desigualdades
territoriais de forma robusta, evitando inferências indevidas a partir de dados não vinculáveis. Contudo, como veremos mais adiante, a perspectiva individual
certamente ajudaria nas predições.""")

# O IPDM - Índice Paulista de Desenvolvimento Municipal - pode ser consultado no seguinte endereço:
# https://repositorio.seade.gov.br/dataset/2be01068-49cc-4cc1-85b8-38bd867aefc4/resource/887a7554-57cd-4a48-8c61-e9ea567b4bfb/download/ipdm.zip
# Os demais dados foram compilados à partir dos indicadores presentes nos seguintes painéis: https://censo2022.ibge.gov.br/panorama/indicadores.html?localidade=3550308&tema=5
# e https://censo2022.ibge.gov.br/panorama/indicadores.html?localidade=3550308&tema=11

# Como o tamanho do arquivo é irrisório, mantemos uma cópia no repositório do GitHub.

PATH_CENSO = "data/censo_2022.csv"

# Carregar os dados
df_censo = pd.read_csv(
    PATH_CENSO,
    sep=",",
    encoding="utf-8",
    low_memory=False
)
display(df_censo.head())
display(df_censo.info())
print("Dados carregados com sucesso!")

Em respeito à LGPD, o INEP dividiu os microdados da edição de 2024 em dois datasets: um com os dados socioeconômicos indivduais dos participantes
e um com os resultados das provas, sem chave de conexão entre eles. Isso limita bastante a pesquisa aplicada: foi preciso, por exemplo,
trabalhar apenas com variáveis a nível municipal, extraídas do Censo 2022, realizado pelo IBGE, que ainda permitem investigar desigualdades
territoriais de forma robusta, evitando inferências indevidas a partir de dados não vinculáveis. Contudo, como veremos mais adiante, a perspectiva individual
certamente ajudaria nas predições.

,municipio,ipdm,rendimento_domiciliar_per_capita,taxa_ensino_superior_completo,taxa_alfabetizacao
0,São Paulo,577,2713.36,27.70,0.97417
1,Guarulhos,527,1643.73,18.27,0.96778
2,Campinas,587,2678.60,27.50,0.97587
3,São Bernardo do Campo,609,2229.41,27.02,0.97650
4,São José dos Campos,604,2276.81,26.22,0.97862

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   municipio                         200 non-null    object
 1   ipdm                              200 non-null    int64
 2   rendimento_domiciliar_per_capita  200 non-null    float64
 3   taxa_ensino_superior_completo     200 non-null    float64
 4   taxa_alfabetizacao                200 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 7.9+ KB

None

Dados carregados com sucesso!

In [120]:
# Arredondar a coluna 'taxa_alfabetizacao' para três casas decimais
df_censo['taxa_alfabetizacao'] = df_censo['taxa_alfabetizacao'].round(3)

display(df_censo.head())
print("Coluna 'taxa_alfabetizacao' arredondada para três casas decimais com sucesso!")

,municipio,ipdm,rendimento_domiciliar_per_capita,taxa_ensino_superior_completo,taxa_alfabetizacao
0,São Paulo,577,2713.36,27.70,0.974
1,Guarulhos,527,1643.73,18.27,0.968
2,Campinas,587,2678.60,27.50,0.976
3,São Bernardo do Campo,609,2229.41,27.02,0.976
4,São José dos Campos,604,2276.81,26.22,0.979

Coluna 'taxa_alfabetizacao' arredondada para três casas decimais com sucesso!

In [121]:
# Realizar o merge dos DataFrames 'base_municipio' e 'df_censo' segundo a chave 'municipio'
df_final = pd.merge(base_municipio, df_censo, on='municipio', how='inner')

# Exibir as primeiras linhas do DataFrame final e suas informações
display(df_final.head())
display(df_final.info())

# Exportar o 'df_final'
df_final.to_csv('data/df_final.csv', index=False)
print("DataFrame 'df_final.csv' exportado com sucesso para 'data/df_final.csv'.")

,municipio,media_notas,total_participantes,desvio_notas,ipdm,rendimento_domiciliar_per_capita,taxa_ensino_superior_completo,taxa_alfabetizacao
0,São Paulo,535.3,55351,74.7,577,2713.36,27.70,0.974
1,Guarulhos,520.4,6145,67.5,527,1643.73,18.27,0.968
2,Campinas,550.6,5403,77.2,587,2678.60,27.50,0.976
3,São Bernardo do Campo,543.4,4967,72.2,609,2229.41,27.02,0.976
4,São José dos Campos,556.4,4231,77.8,604,2276.81,26.22,0.979

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   municipio                         200 non-null    object
 1   media_notas                       200 non-null    float64
 2   total_participantes               200 non-null    int64
 3   desvio_notas                      200 non-null    float64
 4   ipdm                              200 non-null    int64
 5   rendimento_domiciliar_per_capita  200 non-null    float64
 6   taxa_ensino_superior_completo     200 non-null    float64
 7   taxa_alfabetizacao                200 non-null    float64
dtypes: float64(5), int64(2), object(1)
memory usage: 12.6+ KB

None

DataFrame 'df_final.csv' exportado com sucesso para 'data/df_final.csv'.